#!/usr/bin/env python
# Cli search tool for Stack Overflow

"""Sopy.

Usage:
  ./so [<searchTerms>...]
  ./so ( -h | --help)
  ./so (-v | --version)

Options:
  -h --help     Show this screen.
  -v --version  Show version.

"""
from docopt import docopt
import webbrowser

def main(args):
    """
    This is the main function that is called in this script 
    """
    if len(args) > 0:
        query = ' '.join(args)
    else:
        query = ''

    webbrowser.open('https://stackoverflow.com/search?q=' + query)

if __name__=='__main__':
    arguments = docopt(__doc__, version='Sopy 1.0.0')
    main(arguments["<searchTerms>"])


